import Head from "next/head";

// component imports
import LandingPage from "@/components/LandingPage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Promotr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LandingPage />
      </main>
    </>
  );
}
